layout_spectrum: 0.8808985
typography_spectrum: 0.1781239
color:
  saturation: 0.1342769
  lightness: 0.7931307
  brandStrength: 0.7592832
  rhythmicContrast: 0.04617432
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: MMJiu-Jitsu
