name: MMJiu-Jitsu
favicon: null
layout_spectrum: 0.8808985
typography_spectrum: 0.1781239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ecd9b8'
    - '#2e2f34'
    - '#b57727'
  brandStrength: 0.7592832
  lightness: 0.7931307
  saturation: 0.1342769
  rhythmicContrast: 0.04617432
purpose: []
